// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzw2bR27p9YX0yO-Ra8hLKb37VXl3uOpw',
    appId: '1:895294652464:web:17f939730fddb0dab16df5',
    messagingSenderId: '895294652464',
    projectId: 'webrtc-test-dcfd3',
    authDomain: 'webrtc-test-dcfd3.firebaseapp.com',
    storageBucket: 'webrtc-test-dcfd3.appspot.com',
    measurementId: 'G-Q7QYMRB9V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1peuEBv7viHvUtgK82Y2DuNOPhj9El8E',
    appId: '1:895294652464:android:9366e871b1a47941b16df5',
    messagingSenderId: '895294652464',
    projectId: 'webrtc-test-dcfd3',
    storageBucket: 'webrtc-test-dcfd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8a9HLLqf5d2FmLpupbVJvRy2n_-eMFXo',
    appId: '1:895294652464:ios:a10c034040477625b16df5',
    messagingSenderId: '895294652464',
    projectId: 'webrtc-test-dcfd3',
    storageBucket: 'webrtc-test-dcfd3.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8a9HLLqf5d2FmLpupbVJvRy2n_-eMFXo',
    appId: '1:895294652464:ios:03bd2dac8d5ee471b16df5',
    messagingSenderId: '895294652464',
    projectId: 'webrtc-test-dcfd3',
    storageBucket: 'webrtc-test-dcfd3.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
